# Generated by Django 3.2.4 on 2021-06-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodWoodUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wood_type', models.CharField(max_length=50)),
                ('cut_date', models.DateField()),
                ('availability', models.BooleanField()),
                ('arborist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arborist', to='goodwoodapi.goodwooduser')),
                ('woodworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woodworker', to='goodwoodapi.goodwooduser')),
            ],
        ),
    ]
